### ISSUE TITLE
大佬 能不能在urp里面使用

### ISSUE THREAD

**Issue by fenglindubu** [ShiinaManatsu/MMD4UnityTools#1]
按照操作步骤 点击转换无效
能否留个联系方式 方便询问问题

**Comment by ShiinaManatsu** [comment]
生成材质啥的只需要把hdrp的shader换成urp，让对应用熟悉名字改掉即可~

**Comment by ShiinaManatsu** [comment]
> 按照操作步骤 点击转换无效
> 能否留个联系方式 方便询问问题

生成材质啥的只需要把hdrp的shader换成urp，让对应用熟悉名字改掉即可~

**Comment by fenglindubu** [comment]
我使用转换的 好像转换不了 能不能加个q 或者群   我截图请教一下ww

**Comment by ShiinaManatsu** [comment]
> 我使用转换的 好像转换不了 能不能加个q 或者群 我截图请教一下ww

可以加我QQ：625650515

**Comment by fenglindubu** [comment]
申请了 感谢ww
