### ISSUE TITLE
Missing meta files

### ISSUE THREAD

**Issue by eamatamo** [ShiinaManatsu/MMD4UnityTools#3]
When importing the git from the package manager an error pop up due to missing meta files. Can you upload the meta files into a new github tag? 
Sometimes meta files are ignored in the gitignore and it should be removed from that file if order to upload them.

**Comment by ShiinaManatsu** [comment]
> When importing the git from the package manager an error pop up due to missing meta files. Can you upload the meta files into a new github tag? Sometimes meta files are ignored in the gitignore and it should be removed from that file if order to upload them.

Thanks for your notice, I already remove the *.meta from gitignore.
